pipeline:
  name: custom-nab
  identifier: customnab
  template:
    templateRef: customnabtest
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: test2
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      identifier: ShellScript_1
                      type: ShellScript
                      timeout: <+input>.allowedValues(20m)
      variables:
        - name: test_var
          type: String
          value: ""
        - name: second
          type: String
          value: ""
  tags: {}
  projectIdentifier: CDrepro
  orgIdentifier: default
